### ISSUE TITLE
Using the EuiCustomLink in NavBarDrawerGroup

### ISSUE THREAD

**Issue by tobHai** [Imballinst/elastic-react-router-hooks#1]
Is it possible to use the EuiCustomLink in a EuiNavBarDrawerGroup ? 
I'm not really sure how to use it properly in an item of the listItems props.
Thanks !

**Comment by Imballinst** [comment]
Let me try it! I'll post an update once I get the answer.

**Comment by Imballinst** [comment]
I think we can't really use a custom component for the EuiNavBarDrawerGroup.

What we can do is by defining `onClick` event to each element of `listItems`.

https://github.com/Imballinst/elastic-react-router-hooks/blob/9541121397242f41355041e0fd3b09b049e991ec/src/views/Drawer.js#L16-L32

Let me know if this doesn't match your needs!

**Comment by tobHai** [comment]
Thanks for the quick solution!
As you mentioned in the comment sometimes the click event is fired from other elemets like the span.
In my case it was sometimes fired from the `<svg>` or even `<path>` .
So I added: 
```
        if (e.target.localName === 'span') {
            // Sometimes, it's a bit weird, we click on a `span` instead of the link.
            // As such, we need to get the parentNode (the `a` tag).
            nextPathname = e.target.parentNode.href;
        } else if (e.target.localName === 'svg') {
            nextPathname = e.target.parentNode.pathname;
        } else if (e.target.localName === 'path') {
            nextPathname = e.target.parentNode.parentNode.pathname;
        } else {
            // Else, the click is on the `a` tag and we can safely push.
            nextPathname = e.target.pathname;
        }
```

**Comment by Imballinst** [comment]
Awesome! My solution might not be the most elegant one, but I hope it works for you!
